### ISSUE TITLE
[feature request] usage of trained model in python script

### ISSUE THREAD

**Issue by phineas-pta** [chrisociepa/allamo#5]
hello, thanks for the great work

i know that `sample.py`, `sample_api.py` exist but i just want to use the model in a standalone python script

because of the way `AllamoConfiguration.__post_init__()` is defined, i cannot create a new instance `AllamoConfiguration` to use it

is there any way to do it properly without touching the source code?

many thanks

**Comment by chrisociepa** [comment]
Thank you for your feetback!

I've just pushed a small change that allows load/parse configuration conditionally. When you create an object of the AllamoConfiguration class, pass `load_configuration=False` in constructor:
```
config = AllamoConfiguration(load_configuration=False)
```
