### ISSUE TITLE
Sample json file mentioned in README.md is not part of repository

### ISSUE THREAD

**Issue by RDouglasSharp** [chrisociepa/allamo#6]
It would be valuable to provide at least one sample config file...

**Comment by chrisociepa** [comment]
Thank you for this feedback! I've added a sample config [here](https://github.com/chrisociepa/allamo/blob/main/config/train_1B.json). You can find more details on [our website](https://azurro.pl/apt-1b-base-en/) to see how we have trained a 1B model dedicated for the Polish language on a single GPU with 24GB VRAM.
