### ISSUE TITLE
Import_llama_weights.py code bug

### ISSUE THREAD

**Issue by RDouglasSharp** [chrisociepa/allamo#7]
line 137:
import_tokenizer(args.input_tokenizer_path, args.output_data_dir)
should be:
import_tokenizer(args.input_tokenizer_path, args.output_data_dir, args.max_block_size)

**Comment by chrisociepa** [comment]
right, thanks! [fixed](https://github.com/chrisociepa/allamo/commit/1c51e8bd0ff155ef7b2f8b97b8484556e377cbf1)
