### ISSUE TITLE
Consider adding support for openlm-research/open_llama_7b and _3b

### ISSUE THREAD

**Issue by RDouglasSharp** [chrisociepa/allamo#8]
Much larger universe of people who can use truly open Llama variants such as the two models above.  Limiting the code to Facebook-approved academics severely limits its value and reach.

**Comment by chrisociepa** [comment]
@RDouglasSharp thank you for this suggestion! I've just added a new [script](https://github.com/chrisociepa/allamo/blob/main/import_open_llama_weights.py) to import Open LLaMA weights from HF. Even though all parameters are mapped and copied, I was not able to generate a correct response. I didn't have time to investigate the reason, so please keep it in mind when playing with the Open LLaMA weights.
